### ISSUE TITLE
Mod Breaks in Offline Mode on Server

### ISSUE THREAD

**Issue by littlebankz** [IAmSneak/diamond-economy#4] opened 2021-11-29 07:53 UTC
Hi, I'm hosting a small fabric server just to play with my friends and facing a problem when enabling your plugin.

Whenever there is a player joining the server, This line would log out to the console before the player gets disconnected.
`[STDOUT]: No suitable driver found for jdbc:sqlite:./world/./diamondeconomy.sqlite`

I have looked inside the `world` folder and found no file named like that.

Here's my full server log file from starting server -> a player joining -> gets disconnected -> stopping the server. A full list of installed mods should be listed in the log file. Hope this helps you diagnose the problem.

[latest.txt](https://github.com/IAmSneak/diamond-economy/files/7616364/latest.txt)

Any suggestions on this?

**Comment by IAmSneak** [comment] 2021-12-01 14:45
Seems like it is caused by having your server in offline mode, ill try to fix it but I cant guarantee anything.

**Comment by littlebankz** [comment] 2021-12-02 16:16
> Seems like it is caused by having your server in offline mode, ill try to fix it but I cant guarantee anything.

Thanks for checking this out! Maybe sometimes on the weekend, I'll try to enable the online-mode and try again.

**Comment by IAmSneak** [comment] 2022-03-24 17:01
I did check this out at some point and it would require reworking a ton of it. I'm not sure what the best way of getting this to work would be.

**Comment by IAmSneak** [comment] 2022-04-14 00:34
I'm actually not getting this issue in the latest version. I'm going to close this but if you still get this issue comment here so I can reopen it.

**Closed by IAmSneak** 2022-04-14 00:34 UTC
Labels: bug, enhancement
